download datum://id and datum://alias files, run execution locally, using project data files
valohai/valohai-utils pull request #134
Opened 2024-06-21 13:45 UTC by ccschneidr

As discussed in the Continental support channel, we need the possibility to download datum:// input files to run an execution locally. This pull request adds this feature to valohai-utils' download.py.
Using this we were able to run a complete execution, locally.

To test perform the following steps
- log in to valohai with `vh login`
- link a project, if you want to use aliases with `vh link`
- execute python snippet (make sure to replace `my_models_alias` and `01941935-832f-16d4-af69-6a9bf6bf4df6` with existent data)

```python
import valohai

valohai.prepare(
    step="predict",
    default_inputs={
        "model-http": "http://example.com",
        "model-alias": "datum://my_models_alias",
        "model-id": "datum://01941935-832f-16d4-af69-6a9bf6bf4df6",
    },
)

print(valohai.inputs("model-http").path())
print(valohai.inputs("model-id").path())
print(valohai.inputs("model-alias").path())
```

2024-06-24 12:43 UTC, hylje commented
Thank you for the PR, I will adopt the branch to add improvements and add automated test cases.

2024-06-25 07:38 UTC, memona008 requested changes
LGTM! ❇️ some nits though

2024-06-25 07:38 UTC, memona008 commented on tests/test_download.py
> +                "sha256": "88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589",
It can live in a variable to avoid writing it again

2024-06-25 07:38 UTC, memona008 commented on tests/test_download.py
> +        "https://valohai-mnist.s3.amazonaws.com/t10k-images-idx3-ubyte.gz",
Same with the file name
as and use the variable where it's required
`filename = t10k-images-idx3-ubyte.gz `

2024-06-25 08:01 UTC, memona008 approved these changes

2024-06-25 08:02 UTC, merged